services:
  - type: web
    name: mtali-agro-backend
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 4
    envVars:
      - key: DJANGO_SECRET_KEY
        value: ''
      - key: DATABASE_URL
        value: ''
      - key: CLOUDINARY_URL
        value: ''
